<?php
// $Id$

/**
 * Implements hook_xmlsitemap_context().
 */
function domain_xmlsitemap_xmlsitemap_context() {
  $domain = domain_get_domain();
  $context['domain'] = $domain['domain_id'];
  //return $context;
}

function domain_xmlsitemap_xmlsitemap_context_url_options(array $context) {
  $options = array();
  if (isset($context['domain']) && $domain = domain_load($context['domain'])) {
    $options['base_url'] = rtrim($domain['path'], '/');
  }
  return $options;
}

/**
 * Implements hook_xmlsitemap_context_fallback().
 */
function domain_xmlsitemap_xmlsitemap_context_fallback() {
  $context['domain'] = 0;
  return $context;
}

/**
 * Implements hook_xmlsitemap_context_info().
 */
function domain_xmlsitemap_xmlsitemap_context_info() {
  $context['domain'] = array(
    'label' => t('Domain'),
    //'summary callback' => 'locale_language_name',
    'settings callback' => 'domain_xmlsitemap_xmlsitemap_domain_context_settings',
  );
  return $context;
}

function domain_xmlsitemap_xmlsitemap_domain_context_settings(stdClass $sitemap) {
  $domains = domain_domains();
  $options = array();
  foreach ($domains as $domain) {
  	$options[$domain['domain_id']] = $domain['path'];
  }
  $form['domain'] = array(
    '#type' => 'select',
    '#title' => t('Domain'),
    '#options' => $options,
    '#default_value' => issset($sitemap->context['domain']) ? $sitemap->context['domain'] : '',
  );
  return $form;
}
