<?php
// $Id$

/**
 * Implements hook_node_grants_alter().
 */
function domain_xmlsitemap_node_grants_alter(&$grants, $account, $op) {
  if (!empty($account->xmlsitemap_node_access)) {
    unset($grants['domain_site']);
    unset($grants['domain_id']);
    $grants['domain_all'] = array(0);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function domain_xmlsitemap_form_xmlsitemap_sitemap_edit_form_alter(&$form, $form_state) {
  $domains = domain_domains();
  $options = array();
  foreach ($domains as $domain) {
    $options[$domain['domain_id']] = $domain['path'];
  }
  $form['context']['domain'] = array(
    '#type' => 'select',
    '#title' => t('Domain'),
    '#options' => $options,
    '#default_value' => isset($form['#sitemap']['context']['domain']) ? $form['#sitemap']['context']['domain'] : '',
    '#access' => !empty($options),
  );
}

/**
 * Implements hook_query_TAG_alter().
 */
function domain_xmlsitemap_query_xmlsitemap_generate_alter(QueryAlterableInterface $query) {
  $sitemap = $query->getMetaData('sitemap');
  if (!isset($sitemap['context']['domain'])) {
    return;
  }

  // @todo Join here may cause duplicate records. Investigate using a subquery.
  $query->leftJoin('domain_access', 'da', "x.type = 'node' AND x.id = da.nid");
  $query->fields('da', array('gid', 'realm'));
  $or = db_or();
  $or->condition('gid', $sitemap['context']['domain']);
  $or->condition(db_and()->isNull('gid')->condition('gid', 0)->condition('realm', 'domain_site'));
  $query->condition($or);
}
